In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [18]:
# # Reading the text file
# text_path = 'C:/Users/HP/Documents/Fax/Outbox/1661-0.txt'
# with open(text_path, 'r', encoding='utf-8') as file:
#     text = file.read()

In [2]:
text = """Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle
​
This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net
​
​
Title: The Adventures of Sherlock Holmes
​
Author: Arthur Conan Doyle
​
Release Date: November 29, 2002 [EBook #1661]
Last Updated: May 20, 2019
​
Language: English
​
Character set encoding: UTF-8
​
*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES ***
​
​
​
Produced by an anonymous Project Gutenberg volunteer and Jose Menendez
​
​
​
cover
​
​
​
The Adventures of Sherlock Holmes
​
​
​
by Arthur Conan Doyle
​
​
​
Contents
​
​
   I.     A Scandal in Bohemia
   II.    The Red-Headed League
   III.   A Case of Identity
   IV.    The Boscombe Valley Mystery
   V.     The Five Orange Pips
   VI.    The Man with the Twisted Lip
   VII.   The Adventure of the Blue Carbuncle
   VIII.  The Adventure of the Speckled Band
   IX.    The Adventure of the Engineer’s Thumb
   X.     The Adventure of the Noble Bachelor
   XI.    The Adventure of the Beryl Coronet
   XII.   The Adventure of the Copper Beeches
​
​
​
I. A SCANDAL IN BOHEMIA
​
​
I.
​
To Sherlock Holmes she is always _the_ woman. I have seldom heard him
mention her under any other name. In his eyes she eclipses and
predominates the whole of her sex. It was not that he felt any emotion
akin to love for Irene Adler. All emotions, and that one particularly,
were abhorrent to his cold, precise but admirably balanced mind. He
was, I take it, the most perfect reasoning and observing machine that
the world has seen, but as a lover he would have placed himself in a
false position. He never spoke of the softer passions, save with a gibe
and a sneer. They were admirable things for the observer—excellent for
drawing the veil from men’s motives and actions. But for the trained
reasoner to admit such intrusions into his own delicate and finely
adjusted temperament was to introduce a distracting factor which might
throw a doubt upon all his mental results. Grit in a sensitive
instrument, or a crack in one of his own high-power lenses, would not
be more disturbing than a strong emotion in a nature such as his. And
yet there was but one woman to him, and that woman was the late Irene
Adler, of dubious and questionable memory.
​
I had seen little of Holmes lately. My marriage had drifted us away
from each other. My own complete happiness, and the home-centred
interests which rise up around the man who first finds himself master
of his own establishment, were sufficient to absorb all my attention,
while Holmes, who loathed every form of society with his whole Bohemian
soul, remained in our lodgings in Baker Street, buried among his old
books, and alternating from week to week between cocaine and ambition,
the drowsiness of the drug, and the fierce energy of his own keen
nature. He was still, as ever, deeply attracted by the study of crime,
and occupied his immense faculties and extraordinary powers of
observation in following out those clues, and clearing up those
mysteries which had been abandoned as hopeless by the official police.
From time to time I heard some vague account of his doings: of his
summons to Odessa in the case of the Trepoff murder, of his clearing up
of the singular tragedy of the Atkinson brothers at Trincomalee, and
finally of the mission which he had accomplished so delicately and
successfully for the reigning family of Holland. Beyond these signs of
his activity, however, which I merely shared with all the readers of
the daily press, I knew little of my former friend and companion.
​
One night—it was on the twentieth of March, 1888—I was returning from a
journey to a patient (for I had now returned to civil practice), when
my way led me through Baker Street. As I passed the well-remembered
door, which must always be associated in my mind with my wooing, and
with the dark incidents of the Study in Scarlet, I was seized with a
keen desire to see Holmes again, and to know how he was employing his
extraordinary powers. His rooms were brilliantly lit, and, even as I
looked up, I saw his tall, spare figure pass twice in a dark silhouette
against the blind. He was pacing the room swiftly, eagerly, with his
head sunk upon his chest and his hands clasped behind him. To me, who
knew his every mood and habit, his attitude and manner told their own
story. He was at work again. He had risen out of his drug-created
dreams and was hot upon the scent of some new problem. I rang the bell
and was shown up to the chamber which had formerly been in part my own.
​
His manner was not effusive. It seldom was; but he was glad, I think,
to see me. With hardly a word spoken, but with a kindly eye, he waved
me to an armchair, threw across his case of cigars, and indicated a
spirit case and a gasogene in the corner. Then he stood before the fire
and looked me over in his singular introspective fashion.
​
“Wedlock suits you,” he remarked. “I think, Watson, that you have put
on seven and a half pounds since I saw you.”
​
“Seven!” I answered.
​
“Indeed, I should have thought a little more. Just a trifle more, I
fancy, Watson. And in practice again, I observe. You did not tell me
that you intended to go into harness.”
​
“Then, how do you know?”
​
“I see it, I deduce it. How do I know that you have been getting
yourself very wet lately, and that you have a most clumsy and careless
servant girl?”
​
“My dear Holmes,” said I, “this is too much. You would certainly have
been burned, had you lived a few centuries ago. It is true that I had a
country walk on Thursday and came home in a dreadful mess, but as I
have changed my clothes I can’t imagine how you deduce it. As to Mary
Jane, she is incorrigible, and my wife has given her notice, but there,
again, I fail to see how you work it out.”
​
He chuckled to himself and rubbed his long, nervous hands together.
​
“It is simplicity itself,” said he; “my eyes tell me that on the inside
of your left shoe, just where the firelight strikes it, the leather is
scored by six almost parallel cuts. Obviously they have been caused by
someone who has very carelessly scraped round the edges of the sole in
order to remove crusted mud from it. Hence, you see, my double
deduction that you had been out inin vile weather, and that you had a
particularly malignant boot-slitting specimen of the London slavey. As
to your practice, if a gentleman walks into my rooms smelling of
iodoform, with a black mark of nitrate of silver upon his right
forefinger, and a bulge on the right side of his top-hat to show where
he has secreted his stethoscope, I must be dull, indeed, if I do not
pronounce him to be an active member of the medical profession.”
​
I could not help laughing at the ease with which he explained his
process of deduction. “When I hear you give your reasons,” I remarked,
“the thing always appears to me to be so ridiculously simple that I
could easily do it myself, though at each successive instance of your
reasoning I am baffled until you explain your process. And yet I
believe that my eyes are as good as yours.”
​
“Quite so,” he answered, lighting a cigarette, and throwing himself
down into an armchair. “You see, but you do not observe. The
distinction is clear. For example, you have frequently seen the steps
which lead up from the hall to this room.” """

In [3]:
# Initializing the Tokenizer
tokenizer = Tokenizer()

In [4]:
# Fitting the tokenizer on the text
tokenizer.fit_on_texts([text])

In [5]:
print(tokenizer.word_index)

{'the': 1, 'of': 2, '\u200b': 3, 'and': 4, 'i': 5, 'a': 6, 'his': 7, 'to': 8, 'in': 9, 'you': 10, 'he': 11, 'was': 12, 'with': 13, 'it': 14, 'that': 15, '”': 16, 'my': 17, 'as': 18, 'had': 19, 'have': 20, 'holmes': 21, 'but': 22, 'which': 23, 'is': 24, 'for': 25, 'me': 26, 'by': 27, 'not': 28, 'from': 29, 'own': 30, 'at': 31, 'adventure': 32, 'up': 33, 'been': 34, 'see': 35, 'sherlock': 36, 'be': 37, 'on': 38, 'how': 39, 'do': 40, 'your': 41, 'project': 42, 'adventures': 43, 'this': 44, 'ebook': 45, 'gutenberg': 46, 'an': 47, 'case': 48, 'him': 49, 'all': 50, 'one': 51, 'were': 52, 'has': 53, 'himself': 54, 'into': 55, 'upon': 56, 'who': 57, 'out': 58, 'again': 59, 'arthur': 60, 'conan': 61, 'doyle': 62, 'or': 63, 'she': 64, 'always': 65, 'woman': 66, 'her': 67, 'eyes': 68, 'seen': 69, 'would': 70, 'more': 71, 'little': 72, 'so': 73, 'practice': 74, 'know': 75, 'use': 76, 'no': 77, 'almost': 78, 'may': 79, 'give': 80, 'away': 81, 'under': 82, 'scandal': 83, 'bohemia': 84, 'man': 85, 's

In [6]:
# giving every unique word index
len(tokenizer.word_index)

615

In [7]:
input_sequence = []
for sentence in text.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
# input and output combo like
# input                       output
# [145]                         4790
# [145 4790]                    1
# [145 4790 1]                  1020
# so on.....
    for i in range(1,len(tokenized_sentence)):
        input_sequence.append(tokenized_sentence[:i+1])
    

In [8]:
# this is only input data
input_sequence

[[42, 149],
 [42, 149, 1],
 [42, 149, 1, 43],
 [42, 149, 1, 43, 2],
 [42, 149, 1, 43, 2, 36],
 [42, 149, 1, 43, 2, 36, 21],
 [42, 149, 1, 43, 2, 36, 21, 27],
 [42, 149, 1, 43, 2, 36, 21, 27, 60],
 [42, 149, 1, 43, 2, 36, 21, 27, 60, 61],
 [42, 149, 1, 43, 2, 36, 21, 27, 60, 61, 62],
 [44, 45],
 [44, 45, 24],
 [44, 45, 24, 25],
 [44, 45, 24, 25, 1],
 [44, 45, 24, 25, 1, 76],
 [44, 45, 24, 25, 1, 76, 2],
 [44, 45, 24, 25, 1, 76, 2, 150],
 [44, 45, 24, 25, 1, 76, 2, 150, 151],
 [44, 45, 24, 25, 1, 76, 2, 150, 151, 31],
 [44, 45, 24, 25, 1, 76, 2, 150, 151, 31, 77],
 [44, 45, 24, 25, 1, 76, 2, 150, 151, 31, 77, 152],
 [44, 45, 24, 25, 1, 76, 2, 150, 151, 31, 77, 152, 4],
 [44, 45, 24, 25, 1, 76, 2, 150, 151, 31, 77, 152, 4, 13],
 [78, 77],
 [78, 77, 153],
 [78, 77, 153, 154],
 [78, 77, 153, 154, 10],
 [78, 77, 153, 154, 10, 79],
 [78, 77, 153, 154, 10, 79, 155],
 [78, 77, 153, 154, 10, 79, 155, 14],
 [78, 77, 153, 154, 10, 79, 155, 14, 80],
 [78, 77, 153, 154, 10, 79, 155, 14, 80, 14],
 [7

In [10]:
max_len = max([len(x) for x in input_sequence])
max_len

16

In [11]:
# zero padding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequence = pad_sequences(input_sequence, maxlen = max_len, padding = 'pre')

In [12]:
padded_input_sequence

array([[  0,   0,   0, ...,   0,  42, 149],
       [  0,   0,   0, ...,  42, 149,   1],
       [  0,   0,   0, ..., 149,   1,  43],
       ...,
       [  0,   0,   0, ..., 615,   8,  44],
       [  0,   0,   0, ...,   8,  44, 126],
       [  0,   0,   0, ...,  44, 126,  16]])

In [13]:
# Now I separate input and output
x = padded_input_sequence[:,:-1]

In [14]:
y = padded_input_sequence[:,-1]

In [15]:
x.shape

(1220, 15)

In [16]:
y.shape

(1220,)

In [18]:
# one hot encoding on y
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes =616)

In [19]:
y.shape

(1220, 616)

In [20]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
# model training
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [22]:
model = Sequential()
model.add(Embedding(616,100, input_length=20))
model.add(LSTM(150))
model.add(Dense(256,activation='relu'))
model.add(Dense(616, activation = 'softmax'))

C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Embedding, LSTM, Dense

# # Create the Sequential model
# model = Sequential([
#     Embedding(8932, 1000, input_length=20),  # Embedding layer
#     LSTM(150),  # LSTM layer
#     Dense(8932, activation='softmax')  # Dense layer with softmax activation
# ])

# # Compile the model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# # Print the model summary
# model.summary()


In [25]:
x

array([[  0,   0,   0, ...,   0,   0,  42],
       [  0,   0,   0, ...,   0,  42, 149],
       [  0,   0,   0, ...,  42, 149,   1],
       ...,
       [  0,   0,   0, ...,   1, 615,   8],
       [  0,   0,   0, ..., 615,   8,  44],
       [  0,   0,   0, ...,   8,  44, 126]])

In [27]:
model.fit(x,y,epochs = 100)

Epoch 1/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 6s 21ms/step - accuracy: 0.0396 - loss: 6.2965
Epoch 2/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.0416 - loss: 5.6223
Epoch 3/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.0525 - loss: 5.6187
Epoch 4/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.0485 - loss: 5.5063
Epoch 5/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.0544 - loss: 5.3762
Epoch 6/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.0548 - loss: 5.2748
Epoch 7/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.0919 - loss: 5.0503
Epoch 8/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.1043 - loss: 4.8045
Epoch 9/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.0977 - loss: 4.6477
Epoch 10/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.1053 - loss: 4.3861
Epoch 11/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.1127 - loss: 4.1537
Epoch 12/100
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step

In [60]:
text = "has"

# tokenizer
token_text = tokenizer.texts_to_sequences([text])
# padding
padded_token_text = pad_sequences([token_text], maxlen = 16, padding = "pre")
# print(padded_token_text)

# predict
pos = np.argmax(model.predict(padded_token_text))


for word, index in tokenizer.word_index.items():
    if index == pos:
        print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
updated


In [56]:
# text = "project"
# for i in range(5):
#     token_text = tokenizer.texts_to_sequences([text])[0]
#     padded_token_text = pad_sequences([token_text], maxlen=16, padding="pre")
#     prediction = model.predict(padded_token_text)
#     pos = np.argmax(prediction)
    
#     # Reverse mapping from index to word
#     index_word = {v: k for k, v in tokenizer.word_index.items()}
#     predicted_word = index_word.get(pos, None)
    
#     if predicted_word:
#         text += " " + predicted_word
#         print(text)
